spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dataset_db
    username: postgres
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8181

